### PR TITLE
DCP-3434 : Remove old version of EFD when doing a new release to FTP

### PR DESCRIPTION
**Pull request by swatisuman1990**

### CODE REVIEW

**Review by suranjayathilaka — CHANGES_REQUESTED** [review]
1. copy to stg
2. clean old from stg
3. rsync stg to ftp with --delete
4. make symlink in ftp

**Comment by swatisuman1990** [comment]
We cannot do rsync here as the FTP_STG_DIR will also have other files like log and cdp-file-downloader that we dont want to copy to FTP

**Comment by suranjayathilaka** [comment]
you can do selective rsync with includes/excludes

**Comment by swatisuman1990** [comment]
> 1. copy to stg
> 2. clean old from stg
> 3. rsync stg to ftp with --delete
> 4. make symlink in ftp

Made the changes as asked

**Review by suranjayathilaka — APPROVED** [review]

**Pull request merged**
